# Generated by Django 5.1.6 on 2025-02-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuppyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('gender', models.CharField(choices=[('Мальчик', 'Мальчик'), ('Девочка', 'Девочка')], max_length=50, verbose_name='Пол щенка')),
                ('coat_type', models.CharField(choices=[('Длинношерстный', 'Длинношерстный'), ('Гладкошерстный', 'Гладкошерстный')], max_length=100, verbose_name='Тип шерсти')),
                ('color', models.CharField(max_length=100, verbose_name='Желаемый окрас')),
                ('adult_weight', models.CharField(max_length=50, verbose_name='Ожидаемый вес во взрослом возрасте')),
                ('purpose', models.CharField(max_length=255, verbose_name='Цель приобретения собаки')),
                ('temperament', models.CharField(max_length=255, verbose_name='Предпочтительный темперамент')),
                ('has_children', models.BooleanField(verbose_name='Есть ли дети в семье?')),
                ('children_age', models.CharField(blank=True, max_length=255, verbose_name='Возраст детей (если есть)')),
                ('has_pets', models.BooleanField(verbose_name='Есть ли другие питомцы?')),
                ('pets_info', models.TextField(blank=True, verbose_name='Какие питомцы (если есть)?')),
                ('has_experience', models.BooleanField(verbose_name='Есть ли опыт общения с чихуахуа?')),
                ('budget', models.CharField(max_length=100, verbose_name='Бюджет на приобретение щенка')),
                ('delivery_needed', models.BooleanField(verbose_name='Нужна ли доставка в другой город/страну?')),
                ('phone', models.CharField(max_length=20, verbose_name='Контактный телефон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
            ],
        ),
    ]
