# Generated by Django 5.1.6 on 2025-02-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_puppyrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppyrequest',
            options={'verbose_name': 'Заявка на щенка', 'verbose_name_plural': 'Заявки на щенков'},
        ),
    ]
