# Generated by Django 5.1.6 on 2025-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_puppyrequest_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата посещения')),
                ('time', models.TimeField(verbose_name='Время посещения')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
        ),
    ]
